version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: noteapp-postgres
    environment:
      POSTGRES_DB: noteapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 